networkmanager: bump to 1.28.0

diff --git a/extra/networkmanager/build b/extra/networkmanager/build
--- a/extra/networkmanager/build
+++ b/extra/networkmanager/build
@@ -2,20 +2,22 @@
 
 export DESTDIR="$1"
 
-pkg-config --exists libudev || {
-    printf 'udev (or libudev-zero) is required\n'
-    exit 1
-}
-
 for patch in *.patch; do
     patch -p1 < "$patch"
 done
 
+pkg-config --exists nss || {
+    printf 'nss (or gnutls) is required\n'
+    exit 1
+}
+
+# Remove intltool
 sed -i "s/intltool_xml_cmd/['cp', '@INPUT@', '@OUTPUT@']/g" \
     data/meson.build
-
 sed -i '/^intltool/d' \
     meson.build
+
+# Fix includes
 sed -i 's/printf.h/stdio.h/' \
     shared/systemd/src/basic/stdio-util.h
 sed -i 's/ether.h/if_ether.h/' \
@@ -24,7 +26,6 @@ sed -i 's/ether.h/if_ether.h/' \
     libnm-core/nm-utils.c
 sed -i 's/ether.h/if_ether.h/' \
     src/systemd/src/libsystemd-network/network-internal.c
-
 sed -i 's/if_arp.h/if.h/' \
     src/devices/nm-device.c
 sed -i '/#include <limits.h>/a #include <asm/types.h>' \
@@ -39,6 +40,8 @@ sed -i '/#include "nm-core-internal.h"/a #include <linux/if_ether.h>' \
     src/devices/nm-device-bridge.c
 sed -i '/#include <linux\/pkt_sched.h>/a #include <netinet\/if_ether.h>' \
     src/NetworkManagerUtils.c
+
+# musl doesn't support RTLD_DEEPBIND
 sed -i '/RTLD_DEEPBIND/d' \
     shared/nm-glib-aux/nm-json-aux.c
 
@@ -61,8 +64,9 @@ meson \
     -Dnmtui=false \
     -Dtests=no \
     -Dqt=false \
-    -Dhcpcd="${dhcpcd:-true}" \
+    -Dcrypot="${crypto:-gnutls}" \
     -Diwd="${eiwd:-true}" \
+    -Dhcpcd="${dhcpcd:-true}" \
     -Dresolvconf="${eiwd:-true}" \
     -Dsession_tracking="${logind:-elogind}" \
     . build
@@ -70,4 +74,5 @@ meson \
 ninja -C build
 ninja -C build install
 
+install -Dm644 networkmanager.run  "$1/etc/sv/networkmanager/run"
 install -Dm644 networkmanager.conf "$1/etc/NetworkManager/NetworkManager.conf"
